### ISSUE TITLE
[Honeybadger] Error report failed: unknown response from server. code=422

### ISSUE THREAD

**Issue by Junkern** [honeybadger-io/honeybadger-js#523]
## What are the steps to reproduce this issue?
1. Copy the code from https://gist.github.com/Junkern/949e2e6b244650affcd074be76cde8b4 and fill in your api key
2. Execute

## What happens?
The server responds with a 422 HTTP status code with no information on how to send a correct request.

## What were you expecting to happen?
Successful reporting of the error or a description how to avoid the 422 response code

## Any logs, error output, etc?
This is the full `notice` object.

```js
{
  message: 'test',
  name: 'Error',
  context: {},
  projectRoot: '/home/martin/Documents/Selbständigkeit/development/kieser-design/configurator',
  environment: null,
  component: null,
  action: null,
  revision: null,
  stack: 'Error\n' +
    '    at generateStackTrace (/home/martin/Documents/Selbständigkeit/development/kieser-design/configurator/server/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:381:15)\n' +
    '    at Honeybadger.Client.notify (/home/martin/Documents/Selbständigkeit/development/kieser-design/configurator/server/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:584:28)\n' +
    '    at Object.<anonymous> (/home/martin/Documents/Selbständigkeit/development/kieser-design/configurator/server/test.js:12:13)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:986:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n' +
    '    at internal/main/run_main_module.js:17:47',
  backtrace: [
    {
      file: '[PROJECT_ROOT]/server/test.js',
      method: 'Object.<anonymous>',
      number: 12,
      column: 13
    },
    {
      file: 'internal/modules/cjs/loader.js',
      method: 'Module._compile',
      number: 1138,
      column: 30
    },
    {
      file: 'internal/modules/cjs/loader.js',
      method: 'Object.Module._extensions..js',
      number: 1158,
      column: 10
    },
    {
      file: 'internal/modules/cjs/loader.js',
      method: 'Module.load',
      number: 986,
      column: 32
    },
    {
      file: 'internal/modules/cjs/loader.js',
      method: 'Function.Module._load',
      number: 879,
      column: 14
    },
    {
      file: 'internal/modules/run_main.js',
      method: 'Function.executeUserEntryPoint [as runMain]',
      number: 71,
      column: 12
    },
    {
      file: 'internal/main/run_main_module.js',
      method: '<unknown>',
      number: 17,
      column: 47
    }
  ],
  __breadcrumbs: [
    {
      category: 'notice',
      message: 'Honeybadger Notice',
      metadata: [Object],
      timestamp: '2021-01-28T13:18:48.432Z'
    }
  ]
}
```

## What versions are you using?
**Operating System:** `Ubuntu 20.04.1`
**Package Version:** `3.0.1`
**Node Version:** `12.17.0`

**Comment by joshuap** [comment]
@Junkern we're looking into this. 👍

**Comment by joshuap** [comment]
@Junkern try 3.0.2!

**Comment by Junkern** [comment]
@joshuap works! Thank you for the quick fix :)
