### ISSUE TITLE
Errors caught in middleware error handler cause process crash

### ISSUE THREAD

**Issue by npahucki** [honeybadger-io/honeybadger-js#905]
## What are the steps to reproduce this issue?
1. Write code that configures HoneyBadger (v4.3.1), making sure not to disable breadcrumbs: 

```
Honeybadger.configure({
    apiKey: process.env.HONEYBADGER_API_KEY,
    environment,
    enableUncaught: true,
    enableUnhandledRejection: true,
    breadcrumbsEnabled: true,
    debug: false,
    revision: ver,
  });
```

3. Use the HB middleware as the last in the stack:
```
 app.use(Honeybadger.errorHandler);
``` 

## What happens?
Calling `Honeybadger.notify()` works as expected. 
However, when errors occur in Express controllers, there is an error in the HB client library that in turn causes an uncaught exception and hence process termination.

## What were you expecting to happen?
HB does not cause process to crash and successfully sends along breadcrumbs for errors caught in the middleware

## Any logs, error output, etc?
```
[2022-10-03T18:30:38.701Z] [ERROR] Invalid token. {"request":{"path":"/api/jobs","method":"POST","query":{},"params":{},"startTime":"Mon Oct 03 2022 15:30:38 GMT-0300 (Chile Summer Time)"}}
[2022-10-03T18:30:38.707Z] [ERROR] TypeError: Cannot read property 'breadcrumbs' of undefined
    at Honeybadger.Client.addBreadcrumb (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:991:33)
    at Honeybadger.Client.notify (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:847:14)
    at Honeybadger.errorHandler (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:1447:10)
    at Layer.handle_error (/our-app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/our-app/node_modules/express/lib/router/index.js:315:13)
    at/our-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/our-app/node_modules/express/lib/router/index.js:335:12)
    at next (/our-app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/our-app/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/our-app/node_modules/express/lib/router/index.js:315:13)
    at/our-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/our-app/node_modules/express/lib/router/index.js:335:12)
    at next (/our-app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/our-app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/our-app/node_modules/express/lib/router/index.js:315:13)
    at/our-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/our-app/node_modules/express/lib/router/index.js:335:12)
    at next (/our-app/node_modules/express/lib/router/index.js:275:10)
    at Strategy.strategy.error (/our-app/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at verified (/our-app/node_modules/passport-http-bearer/lib/strategy.js:118:28)
    at/our-app/config/authentication.js:79:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {"source":"console","stacktrace":"Stacktrace\n    at Function.logerror (/our-app/node_modules/express/lib/application.js:630:43)\n    at processImmediate (internal/timers.js:463:21)\n    at process.topLevelDomainCallback (domain.js:138:15)\n    at process.callbackTrampoline (internal/async_hooks.js:124:14)"}
/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:991
        var breadcrumbs = store.breadcrumbs;
                                ^

TypeError: Cannot read property 'breadcrumbs' of undefined
    at Honeybadger.Client.addBreadcrumb (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:991:33)
    at Honeybadger.Client.notify (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:847:14)
    at process.honeybadgerUncaughtExceptionListener (/our-app/node_modules/@honeybadger-io/js/dist/server/honeybadger.js:1383:28)
    at process.emit (events.js:326:22)
    at process.EventEmitter.emit (domain.js:483:12)
    at process._fatalException (internal/process/execution.js:165:25)

Process finished with exit code 7

``` 

## Any other comments?
We worked around the issue for now turning off breadcrumbs:
```
Honeybadger.configure({
    ...
    breadcrumbsEnabled: false,
    ...
  });
```

## What versions are you using?
**Operating System:** …
MacOS (local env) and Ubuntu 20.04 (Server)

**Package Name:** …
**Package Version:** …
4.3.1

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c9rkx)

**Comment by npahucki** [comment]
I forgot to mention this strange fact: This problem appeared when we upgraded from Node 10 to Node 12.
